### ISSUE TITLE
Allow usage of pifinder without GPS

### ISSUE THREAD

**Issue by mrosseel** [brickbots/PiFinder#112]
When an observer forgets the GPS stick at home, the pifinder should still be able to function correctly.

* find out if this is possible today
* make sure it is possible by using the lat/lon in the config file and the time of the pi. It is the unfortunate observers' task to set these things correctly

Bonus points would be for a future web server to allow changing these parameters via the web interface.

**Comment by brickbots** [comment]
This is now possible as of Release 1.8.0 🙌
