### ISSUE TITLE
Add an adapter for Rigel Quikfinder base

### ISSUE THREAD

**Issue by jscheidtmann** [brickbots/PiFinder#177]
I am going to add an adapter for a Rigel Quikfinder base:

 * create directories case/adapters/quikfinder
 * change case/README.md
 * reflect this change in documentation under "Mounting".

Shortcoming of this adapter: One cannot orient the PiFinder perpendicular to the ground, as recommended.

Looks like this: 
![image](https://github.com/brickbots/PiFinder/assets/19821951/094c7eb8-7d38-4eed-b715-8606c7bac45b)

**Comment by brickbots** [comment]
This is a great idea/addition.  What software are you using to model this in?  Perhaps we can merge the pivot portion of the existing foot with this connector?

**Comment by jscheidtmann** [comment]
I used OnShape, free version. I believe you're using Fusion360?

**Comment by jscheidtmann** [comment]
Here‘s the first construction:
![IMG_2082](https://github.com/brickbots/PiFinder/assets/19821951/74b5401a-5dda-4ab8-8314-22ebdf1ba9ad)

Idea is to to be compatible to the dovetail top. Will print it tomorrow, to check dimensions.
