### ISSUE TITLE
'Align camera' target locations persistent if no target is selected

### ISSUE THREAD

**Issue by cdSheriff** [brickbots/PiFinder#189]
Flow to reproduce bug:
1. move telescope to sky view 'A'
2. initiate **Align** function from _Camera_ screen
3. cancel **Align** function without selecting object
4. move telescope to sky view 'B'
5. initiate **Align** function from _Camera_ screen
6. **objects 1,2,3 are persistent in screen location from sky view A, no relation to sky view B**

HW/SW:
- RPi 4
- 1.11.2 fresh build from .img

**Comment by brickbots** [comment]
This should be resolved with the new alignment system :+1:
