### ISSUE TITLE
Populate_wifi_networks() in sys_utils fails when networks or password contain equal signs

### ISSUE THREAD

**Issue by jscheidtmann** [brickbots/PiFinder#238]
Sys_utils.py line 50 uses string.split(„=„) which is wrong and fails, if any line contains additional equal signs.

**Comment by mrosseel** [comment]
should probably refactor this to use dbus communication to networkmanager - cleaner than changing config files and we might be able to avoid some reboots

**Comment by jscheidtmann** [comment]
Maybe you can create a different ticket for that? 
This one needs fixed, as this kills the process and user(s) on Discord report(s) a hanging PiFinder.

**Comment by mrosseel** [comment]
working on it

**Comment by brickbots** [comment]
> should probably refactor this to use dbus communication to networkmanager - cleaner than changing config files and we might be able to avoid some reboots

When we finally finish moving to the new version of Raspberry Pi OS, there is a totally new network management system.  I have it roughed in a Bookworm branch, but it's been a long time..... So let's not make any big changes here until we move to the new OS

**Comment by brickbots** [comment]
Merged #239
