### ISSUE TITLE
Docs generation is not automated

### ISSUE THREAD

**Issue by jscheidtmann** [brickbots/PiFinder#257]
It seems like a git workflow to build and upload the documentation to readthedocs.io is not in the code repository. 
I looked at the history of the .github folder, but it seems it was never there. 

Do you want me to have a look?

**Comment by jscheidtmann** [comment]
Note that the documentation claims that this automation exists.

**Comment by brickbots** [comment]
Hi @jscheidtmann.  This is indeed automated, but not in the way you are thinking (build + push).  readthedocs.io has systems building from source in a github.com repo which pull the repo and build via their machinery.  Each time a commit is made to the main or release branch the documentation on readthedocs is updated according to the config in the .readthedocs.yaml file

**Comment by jscheidtmann** [comment]
Argh. Should have checked their docs, first! :-D
