### ISSUE TITLE
Make sure the database is fully reproducible from the sources

### ISSUE THREAD

**Issue by mrosseel** [brickbots/PiFinder#28]
Make sure that there's an easy command to generate the database, and that the result is bit-for-bit the same as the one which is checked in.
(pretty sure this is not the case because I fixed whitespace issues in the db)

**Comment by brickbots** [comment]
Yes, this is definitely on me.... I was not anticipating so many awesome contributions from folks.  I'll work to get all the source data files checked in :+1:

**Comment by mrosseel** [comment]
I'll make a PR which you can add the files to, I'm already changing the
setup python file to make the db from scratch

**Comment by brickbots** [comment]
Awesome!  Sounds great.  Thank you again for all the great work. On a related note, I'd like to figure out a nice way to decode those shorthand NGC observation notes.  I took a run at it at one point, but they are not very consistent and difficult to parse :-/   Now that the catalog screen is becoming more capable, having more human friendly descriptions would be nice.  I'll have to check on that again soon :-)

**Comment by mrosseel** [comment]
wip in #30

**Comment by mrosseel** [comment]
#30 has been merged! The checked-in database is now freshly generated using setup.py. Anything missing should be fixed in setup.py, not in the database.

**Comment by brickbots** [comment]
Thank you for the great work here cleaning up some of the mess I generated early on!  🙏
