### ISSUE TITLE
Better WiFi config via web interface 

### ISSUE THREAD

**Issue by brickbots** [brickbots/PiFinder#68]
It would be wonderful to have a more approachable way to manage wpa_supplicant.conf settings.  A web interface allowing the removal, addition, and re-ordering of Wifi networks would be fantastic.  This would remove the last 'technical' activity that PiFinder owners might need to perform.

**Comment by brickbots** [comment]
This could also include changing the access point name to prevent in-the-field conflicts

**Comment by mrosseel** [comment]
> This could also include changing the access point name to prevent in-the-field conflicts

you mean that the AP sent out by the pifinder has a unique number to distinguish it? Ties in with the unique number discussion maybe? Or some hash of the mac address for now.
