### ISSUE TITLE
Tetra3 doesn't like trees

### ISSUE THREAD

**Issue by mrosseel** [brickbots/PiFinder#71]
Either Tetra3 doesn't like trees or there are not enough stars resolved:

![23774c96_diag_001 png](https://github.com/brickbots/PiFinder/assets/1465310/1a6a6a1b-ded6-4f77-85cd-3a2f71333325)

**Comment by smroid** [comment]
I've developed an alternative to Tetra3's star extraction and centroiding step, at https://github.com/smroid/StarGate. When applied to the tree image in this bug, it finds all of the real stars with no false stars in the tree clutter, and the resulting centroid list solves with Tetra3.

I would like to include the test image above in the stargate repo's test_data directory. May I have permission to do so, and to whom should I credit that image?

**Comment by brickbots** [comment]
Hi Hi!

I've been watching your project with interest, thanks for testing it against this pathological image.  I'm pretty sure @mrosseel took the original if you are looking for permission/attribution.

I'm not super-familiar with rust, but the gRPC interface looks simple enough.  I might see if I can get up to speed enough to get the StarGate installed and running to give it a few tests.

**Comment by mrosseel** [comment]
solved by #131
